"""Is a Jev-selected summary better than a written one, and better than nothing?

probe_summary.py measured the SDF document against its page and found it losing:
on the questions that actually need the page, an abstractive summary answered
0.500 while the same number of tokens of raw page text answered 0.900. The
conclusion was that a brief plus key points keeps what a page is about and throws
away what it says.

This tests the artefact that follows from that. Jev cannot write a summary, but it
can select one: score every sentence on the page for whether it carries something
a reader would need, keep the best that fit the budget (jev_summarize.py). The
result is copied text, so it cannot hallucinate and every line stays findable in
the source.

Five contexts at matched token budgets, all questions answered by Jev:

    full page        the reference. Not truth, just what the page supports.
    Jev-selected     the artefact under test.
    written summary  what the SDF pipeline produces today, same budget.
    same-size page   plain truncation. The control that decides everything.
    url and title    the floor. Questions answerable here test nothing.

Questions are generated by a local model, which is harness, not product. Their
answer key is never used: the reference is what Jev answers holding the page.

    python probe_jev_summary.py <model.gguf> [n]
"""
from __future__ import annotations

import json
import re
import sys
import time

import numpy as np

from probe_extract import FEEDS, feed_urls_for
from probe_jev import ENDPOINT, MODEL, api_key
from jev_summarize import summarize
from sdf_convert import UA, allowed, api_url

LETTERS = ("A", "B", "C", "D")
CONDS = ("full page", "Jev-selected", "written summary", "same-size page",
         "url and title")


def fetch(url):
    import httpx
    import trafilatura
    if not allowed(url):
        return None
    r = httpx.get(api_url(url), headers={"User-Agent": UA}, timeout=30,
                  follow_redirects=True)
    if r.status_code != 200:
        return None
    text = trafilatura.extract(r.text, include_comments=False,
                               include_tables=True) or ""
    if len(text) < 3000:
        return None
    m = re.search(r"<title[^>]*>(.*?)</title>", r.text, re.S | re.I)
    return {"url": url, "text": text,
            "title": " ".join(m.group(1).split()) if m else url,
            "html_kb": len(r.text.encode()) / 1024}


def as_json(s):
    m = re.search(r"\{.*\}|\[.*\]", s or "", re.S)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except json.JSONDecodeError:
        return None


def gen(chat, prompt, max_tokens=900):
    return "".join(chat.stream([dict(role="user", content=prompt)],
                               max_tokens=max_tokens, temperature=0.0))


def make_questions(chat, p, k=6):
    out = gen(chat, f"{p['text'][:9000]}\n\nWrite {k} multiple-choice questions "
                    "about SPECIFIC DETAILS buried in the body of this page: exact "
                    "numbers, named mechanisms, conditions, limits, sequences of "
                    "steps. A reader who saw only the title and URL must have no "
                    "way to answer. Each needs four plausible options, only one "
                    "supported by the page. Reply with JSON only: "
                    '[{"q": "...", "options": ["...", "...", "...", "..."]}]')
    qs = as_json(out)
    if not isinstance(qs, list):
        return []
    good = []
    for it in qs:
        if isinstance(it, dict) and isinstance(it.get("q"), str) \
                and isinstance(it.get("options"), list) and len(it["options"]) == 4:
            good.append({"q": it["q"].strip()[:220],
                         "options": [str(x).strip()[:90] for x in it["options"]]})
    return good[:k]


def written_summary(chat, p, budget_tokens):
    """What the pipeline does now, at the same budget as the selection."""
    n_points = max(3, budget_tokens // 45)
    d = as_json(gen(chat, f"{p['text'][:9000]}\n\nSummarise this page as "
                          '{"brief": "one sentence", "detailed": "three sentences", '
                          f'"key_points": [{n_points} short strings]}}. '
                          "Reply with JSON only.", 700))
    return json.dumps(d if isinstance(d, dict) else {}, ensure_ascii=False)


def ask_jev(client, key, context, qs):
    """One request: every question against the same state."""
    state = {"context": context,
             "questions": [{"q": it["q"], "options": it["options"]} for it in qs]}
    questions = {
        f"q{i}": {
            "type": "choice",
            "instructions": {
                "task": f"Answer question {i} in `questions` using only `context`.",
                "question": qs[i]["q"],
                "guidance": "Choose the letter whose option the context supports. "
                            "If the context does not settle it, choose the most "
                            "likely option anyway.",
            },
            "criteria": {L: o for L, o in zip(LETTERS, qs[i]["options"])},
        } for i in range(len(qs))}
    r = client.post(ENDPOINT, json={"state": state, "model": MODEL,
                                    "questions": questions},
                    headers={"Authorization": f"Bearer {key}"})
    r.raise_for_status()
    d = r.json()
    return ([d["answers"][f"q{i}"]["choice"] for i in range(len(qs))],
            (d.get("usage") or {}).get("input_tokens", 0))


def main():
    import httpx
    from yantrik_inference import open_model

    gguf = sys.argv[1]
    n = int(sys.argv[2]) if len(sys.argv) > 2 else 12
    budget = int(sys.argv[3]) if len(sys.argv) > 3 else 500

    _, chat = open_model(gguf, decide_ctx=8192, decide_seq=2, chat_ctx=16384)
    key = api_key()

    per = [feed_urls_for(f) for f in FEEDS]
    urls = [u for row in zip(*[q + [None] * 20 for q in per]) for u in row if u]
    urls = list(dict.fromkeys(urls))
    print(f"  {len(urls)} candidate URLs across {len(FEEDS)} feeds; "
          f"using the first {n} that fetch. Budget {budget} tokens.\n")

    rows, hard = [], {k: [] for k in CONDS}
    sel_s, toks = [], {k: [] for k in CONDS}
    with httpx.Client(timeout=120) as client:
        for u in urls:
            if len(rows) >= n:
                break
            try:
                p = fetch(u)
            except Exception:                             # noqa: BLE001
                p = None
            if not p:
                continue
            qs = make_questions(chat, p)
            if len(qs) < 4:
                continue
            try:
                sel = summarize(client, key, p["url"], p["title"], p["text"], budget)
            except Exception as e:                        # noqa: BLE001
                print(f"  selection failed for {u[8:50]}: {type(e).__name__}")
                continue
            if not sel["sentences"]:
                continue
            sel_s.append(sel.get("seconds", 0))

            picked = " ".join(sel["sentences"])
            chars = int(budget * 4)
            conds = {
                "full page": p["text"],
                "Jev-selected": picked,
                "written summary": written_summary(chat, p, budget),
                "same-size page": p["text"][:len(picked)],
                "url and title": f"URL: {p['url']}\nTitle: {p['title']}",
            }
            try:
                ans = {}
                for kname, ctx in conds.items():
                    a, t = ask_jev(client, key, ctx, qs)
                    ans[kname] = a
                    toks[kname].append(t)
            except Exception as e:                        # noqa: BLE001
                print(f"  answering failed for {u[8:50]}: {type(e).__name__}")
                continue

            ref = ans["full page"]
            needs = [f != r for f, r in zip(ans["url and title"], ref)]
            for kname, v in ans.items():
                hard[kname] += [x == y for x, y, nd in zip(v, ref, needs) if nd]
            rows.append({kname: float(np.mean([x == y for x, y in zip(v, ref)]))
                         for kname, v in ans.items()} | {"nq": len(qs)})
            print(f"  {p['url'][8:60]:60s} {len(qs)}q  "
                  + "  ".join(f"{kname.split()[0][:4]}={rows[-1][kname]:.2f}"
                              for kname in CONDS[1:4]))

    if not rows:
        print("  no usable pages")
        return
    nq = sum(r["nq"] for r in rows)
    print(f"\n  {len(rows)} pages, {nq} questions, all answered by Jev\n")
    print(f"  {'context given':18s} {'tokens':>8s} {'all questions':>14s}")
    for kname in CONDS:
        print(f"  {kname:18s} {np.mean(toks[kname]):8.0f} "
              f"{np.mean([r[kname] for r in rows]):14.3f}")

    nh = len(hard["Jev-selected"])
    if nh:
        print(f"\n  restricted to the {nh} questions the URL and title do NOT answer:\n")
        print(f"  {'context given':18s} {'agreement':>10s}")
        for kname in ("Jev-selected", "written summary", "same-size page"):
            print(f"  {kname:18s} {np.mean(hard[kname]):10.3f}")

    print(f"\n  selection took {np.mean(sel_s):.2f} s per page")
    print("  The control is 'same-size page'. A summary earns its keep only where")
    print("  it beats plain truncation to the same number of tokens.")


if __name__ == "__main__":
    main()
